### ISSUE TITLE
请将 hostapd-wpe 更新到最新上游版本

### ISSUE THREAD

**Issue by ghost** [woolabs/Woobuntu#12]
https://github.com/woolabs/Woobuntu/blob/master/woobuntu_chroot_build.sh#L852

这里的 hostapd-wpe 使用的是 https://github.com/hph86/hostapd-wpe ，目前只支持到 hostapd-2.5 。但它的上游 https://github.com/OpenSecurityResearch/hostapd-wpe 已经更新并支持最新的 hostapd-2.6 ，所以是不是能更新下呢？

**Comment by lxj616** [comment]
已代码上更新，在build测试，感谢您的提醒
