### ISSUE TITLE
既然是国人那就写中文了

### ISSUE THREAD

**Issue by springhack** [woolabs/Woobuntu#3]
建议WIne QQ这种东西还是不要自带了，幸好GIthub有限制😂

**Comment by lxj616** [comment]
其他工具都是直接脚本内现场下载的，但是由于wine qq没有官方的下载地址，因此不能直接固定链接下载，mdk3同理，以后会考虑想办法完全自动化wine qq的集成，当然你将来也可以把wine qq注释掉取消集成

您还有其他的建议吗

**Comment by lxj616** [comment]
计划提供更加方便的系统定制方式，工具按照体积大小和常用程度分类，使用户装机后再定制所需的工具

**Comment by springhack** [comment]
科科，建议不自带WineQQ是基于系统稳定性考虑。至于考虑自动化流程，我觉得可以设置选项选择集成那些组件，类似Cygwin的安装，暂时就这些。

**Comment by lxj616** [comment]
已加入软件中心，不再集成wine-qq，安装完成后可通过woobuntu-installer快速安装wine-qq等工具
